ml4ai/skema

skema/skema-rs/mathml/src/graph.rs, skema/skema-rs/mathml/src/parsing.rs, skema/skema-rs/mathml/tests/test01.xml
This PR implements a couple of small changes to the `mathml` package:
- Reduces code duplication in `graph.rs`
- Autoformats `parsing.rs` and removes unused import
- Changes tabs to spaces in `test01.xml`
=> Updates to mathml package

skema/skema-rs/mathml/src/ast.rs, skema/skema-rs/mathml/src/bin/parse_mathml.rs, skema/skema-rs/mathml/src/graph.rs, skema/skema-rs/mathml/src/lib.rs, skema/skema-rs/mathml/src/normalization.rs, skema/skema-rs/mathml/src/parsing.rs
This PR implements collapsing subscripts in presentation MathML documents. To get this to work, a number of other refactoring steps were needed, the most significant of which is to convert the arguments of the enum variants in `MathExpression` from `&'a str` to `String` in order to have them own the data themselves rather than just pointers to it. This makes traversal and in-place modification much easier, at the cost of introducing `.to_string()` method calls in the test functions.
Unnormalized presentation MathML expression:
Normalized expression:
The implementation is a minimal, proof of concept one, so it may not be able to handle more complicated expressions, but at least it works with the CHIME SIR update equation.
=> Subscript collapsing

skema/skema-rs/Cargo.lock, skema/skema-rs/comment_extraction/src/languages/python.rs, skema/skema-rs/skema/Cargo.toml, skema/skema-rs/skema/README.md, skema/skema-rs/skema/src/bin/skema_service.rs, skema/skema-rs/skema/src/lib.rs, skema/skema-rs/skema/src/services.rs, skema/skema-rs/skema/src/services/comment_extraction.rs, skema/skema-rs/skema/tests/test_service.rs
This PR adds a first cut at a SKEMA web service for the Rust components of SKEMA. Currently, it only supports comment extraction, but we can build upon it to expose other functionality via a REST API.
=> skema-rs web service

skema/code2fn/client.py
The current version of the example code2fn client program `client.py` is slightly outdated and has an issue where the request JSON is being output to the console instead of the response JSON being written to file.
This pull request updates the client so that the response JSON is now written to a file with the naming convention: `{args.system_name}--Gromet-FN-auto.json`
=> Updating code2fn client.py to properly write output JSON to file

.drone.yml
This PR activates the equation reading (ER) CI pipeline by uncommenting the relevant portion in `.drone.yml`. As it turns out, the ER CI pipeline takes about 16 minutes on kraken, but it works. May look into speeding it up later if we have the time.
=> Activating equation reading CI pipeline

skema/code2fn/client.py, skema/code2fn/server.py
This PR updates the Code2FN service and example client.
- Instead of providing separate host and port arguments, we just use a URL argument in client.py
- Adds a ping endpoint for testing the health of the service
- changes the main endpoint from `/` to `/fn-given-filepaths`
=> Code2FN updates

skema/utils/module_to_fn_collection.py
Creates a util function in utils/module_to_fn_collection.py which is used to wrap a single GroMEt FN module into a GroMEtFNModuleCollection shell.
=> GroMEt module to GroMEtFNModuleCollection PR

skema/program_analysis/python2cast.py, skema/program_analysis/script_functions.py, skema/utils/script_functions.py
If code that is unable to be parsed by the AST library is submitted, the program can end up in a state such that the current directory does not exist, causing further evocations to fail.
This should ensure that we always return to the original directory regardless of failure.
=> Fix bug where CWD is lost

skema/gromet/primitive_map.yaml
Adds the Gromet primitive_map (primitive_map.yaml) to the Gromet directory. It was previously located in the automates repository and never transitioned to Skema.
Also adds primitives for the following types:
- Graph
- Node
- Edge 
- DataFrame
=> Adding gromet primitive map to Gromet directory

skema/text_reading/text_reading/src/main/resources/org/ml4ai/skema/text_reading/grammars/locations.yml, skema/text_reading/text_reading/src/main/resources/org/ml4ai/skema/text_reading/grammars/vars.yml, skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/CosmosTextReadingPipeline.scala, skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/OdinEngine.scala, skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/TextReadingPipeline.scala, skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/apps/AnnotateCosmosJsonFiles.scala, skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/apps/ExtractAndAlign.scala, skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/attachments/AutomatesAttachment.scala, skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/scenario_context/ContextEngine.scala, skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/scenario_context/CosmosOrderer.scala, skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/scenario_context/MentionOrderer.scala, skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/serializer/AutomatesJSONSerializer.scala, skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/utils/MentionUtils.scala, skema/text_reading/text_reading/src/test/scala/org/ml4ai/skema/test/TestUtils.scala, skema/text_reading/text_reading/src/test/scala/org/ml4ai/skema/text_reading/text/TestDescriptions.scala, skema/text_reading/text_reading/src/test/scala/org/ml4ai/skema/text_reading/text/TestIdentifiers.scala, skema/text_reading/text_reading/src/test/scala/org/ml4ai/skema/text_reading/text/TestParameterSetting.scala, skema/text_reading/text_reading/src/test/scala/org/ml4ai/skema/text_reading/text/TestParameterSettingInterval.scala, skema/text_reading/text_reading/webapp/app/controllers/HomeController.scala
This is the first implementation of Scenario Context.
The two main abstractions are: `ContextEngine`, which looks around a window of sentences in order to attach location and time scenario context to relation and event mentions; and `MentionOrderer` which is used to abstract the notion of a linear partial ordering of appearance for the mentions, regardless of the source. This way, we can sort the mentions that come from a Cosmos document, which has pages and blocks within pages, and look around efficiently at the time of context resolution.
=> Scenario Context

skema/skema-rs/mathml/src/expression.rs
This PR renames the 'op' field to 'ops' in the PreExp and Expression structs, to better reflect that the fields represent vectors of operators rather than single operators.
=> Rename 'op' field to 'ops' in PreExp and Expression structs

docker-compose.skema-rs.yml
This PR fixes `docker-compose.skema-rs.yml` to have the correct build context and Dockerfile.
=> Fixing docker-compose.skema-rs.yml

.github/workflows/docs.yml
The previous version of the docs publishing workflow was invalid (it had a stray `needs:` entry from a related workflow).
- Remove `needs:` entry
- Use haskell/actions/setup@v2
- Add caching to docs workflow for faster builds
- Before caching 🐢 : [~30 minutes](https://github.com/ml4ai/skema/actions/runs/4623644132)
- After caching 🦔 : [~3 minutes](https://github.com/ml4ai/skema/actions/runs/4625146649)
- Use `/home/runner/work/skema/skema` as an alternative to `GITHUB_WORKSPACE`
=> Fix to doc workflow and make use of deps caching 

skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/CosmosTextReadingPipeline.scala, skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/PlainTextFileTextReadingPipeline.scala, skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/TextReadingPipelineWithContext.scala, skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/apps/AnnotateCosmosJsonFiles.scala, skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/apps/AnnotatePlainTextFiles.scala, skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/apps/ExtractAndExport.scala, skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/serializer/SkemaJSONSerializer.scala, skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/utils/AlignmentJsonUtils.scala, skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/utils/CommandLineArgumentParser.scala, skema/text_reading/text_reading/src/test/scala/org/ml4ai/skema/text_reading/serialization/TestConjDescrSerialization.scala, skema/text_reading/text_reading/src/test/scala/org/ml4ai/skema/text_reading/serialization/TestCrossSentenceSerialization.scala, skema/text_reading/text_reading/webapp/app/controllers/HomeController.scala, skema/text_reading/text_reading/webapp/conf/routes, skema/text_reading/text_reading/webapp/public/schema/api-v1.yaml
This PR addressed #153
- Adds an app to process plain text files, in addition to the existing one that reads Cosmos Json files
- Adds an in-memory text reading pipeline with scenario context (for use in the web api)
- Renames the JSON serializer from `AutomatesJSONSerializer` to `SkemaJSONSerializer`
=> Plain text entry point

data/TIE_GCM/cons.F, data/TIE_GCM/cpktkm.F
Adding `cons.F` and `cpktkm.F` Fortran source files from the TIE_GCM space weather model to the data directory.
Note: For some reason, Github's syntax highlighter is having issues with these files, but they are valid and parsable Fortran files.  
Resolves issue #177
=> Adding currently supportd space weather files from TIE_GCM model

skema/program_analysis/single_file_ingester.py, skema/program_analysis/snippet_ingester.py
Fixes filename truncation bug when running the pipeline with single_file_ingester.py. 
Fixes additional bug in single_file_ingester where the `path` argument was previously optional. 
Creates a new ingestion script snippet_ingester.py to ingest code snippets instead of files. Its two arguments are the source string itself and a file extension associated with the snippet language (We need this to pass down the pipeline so we know which language we are working with). 
For example:
```bash
python snippet_ingester.py "x=2" ".py"
```
Resolves #202
=> [CODE2FN] single_file_ingester fixes and snippet_ingester creation 

skema/text_reading/text_reading/annotate_cosmos_json
Right now the paths are hardcoded. I am making the script more flexible by taking these as arguments because input and output files are copied in a scratch directory in the ht condor cluster.
=> Taking input and output paths as arguments.

.github/workflows/docker.yml
This GitHub Action is intended to build the following images whenever a PR is opened:
- `lumai/askem-skema-py` (contains program analysis, moviz, etc. components)
- `lumai/askem-skema-rs`
- `lumai/askem-skema-text-reading`
- `lumai/askem-skema-img2mml`
Any push (including a merged PR) to `main` will publish those four images to public repos on Dockerhub.  Each image will be tagged with a) `latest` and b) its short Git commit hash.
Resolves #221
=> Build and publish project docker images to lumai dockerhub namespace

.github/workflows/docker.yml
The text-reading image fails to push after exhausting all available disk space.  This step is aimed at freeing up some additional space.
=> Free disk space for GitHub Actions

.github/workflows/docker.yml
Builds and publishes docker images for the default branch.  Images are tagged with short commit hash, latest, and any Git tags.
Resolves #228.
=> [docker] Build, tag, and publish images whenever a git tag is pushed

.github/workflows/docker.yml
This PR ensures that the most recent image published to Docker Hub is tagged with `latest`.
=> Ensure `latest` tag is always published

docs/coverage/index.md
Test coverage reports for Python are now published to our project site: https://ml4ai.github.io/skema/coverage/python/index.html
Because of an oversight in the project .gitignore, https://ml4ai.github.io/skema/coverage/  is returning a 404.  This PR ensures https://ml4ai.github.io/skema/coverage/ resolves to an index.html.
=> index page for test coverage reports

skema/skema-rs/Cargo.lock, skema/skema-rs/comment_extraction/src/bin/extract_comments.rs, skema/skema-rs/comment_extraction/src/conventions.rs, skema/skema-rs/comment_extraction/src/extraction.rs, skema/skema-rs/comment_extraction/src/lib.rs, skema/skema-rs/skema/Cargo.toml, skema/skema-rs/skema/src/bin/skema_service.rs, skema/skema-rs/skema/src/services/comment_extraction.rs
This PR adds a REST API endpoint to the skema-rs service for extracting comments from a zipfile.
Example curl invocation:
```
curl -X POST localhost:8080/get-comments-from-zipfile --data-binary "@data.zip"
```
=> Added endpoint for extracting comments from zipfile

README.md, skema/skema_py/server.py
The code2fn endpoints claim to return JSON, but actually return strings.  Rather than converting dictionaries to JSON-like strings, this PR delegates the process to FastAPI for predictable return types.
=> Correct return type for PA endpoints

skema/gromet/__init__.py, skema/program_analysis/multi_file_ingester.py, skema/program_analysis/script_functions.py, skema/skema_py/server.py
A couple of PA fields were marked as optional.  Setting these to `None` (as opposed to an empty string) led to errors.  This PR addresses cases where `None` is used.
I've also included a change related to #270 to consistently reference the current gromet version.
=> Gracefully handle optional fields in PA

skema/program_analysis/comments.py, skema/program_analysis/fn_unifier.py, skema/skema_py/server.py
- Adds /fn-supported-file-extensions endpoint which returns the file extensions that are currently supported by the code2fn pipeline
- system_to_gromet() now returns a Dict instead of a raw JSON string. The placeholder json.load() calls have been removed from fn_given_filepaths and fn_given_filepaths_zip
- Updates description of System fields
- Updates endpoint descriptions and examples
=> Add /fn-supported-file-extensions endpoint and additional skema-py endpoint updates

Dockerfile.skema-py, pyproject.toml, skema/rest/schema.py
Quick fix to address an error encountered when launching the REST API (related to use of `Literal` with pydantic/fastapi).  Relates to https://github.com/pydantic/pydantic/issues/5821#issuecomment-1559196859
=> Resolves issue related to use of Literal

skema/img2mml/eqn2mml.py, skema/rest/workflows.py
End-to-end workflows are still a work in progress.  This PR includes changes to help understand where these workflows still fail (ex. latex/images -> mml -> AMR).
- Added error handling for `/workflows` for easy debugging
- Created helper method for handling base64 encoded images
=> [integration] Error handling for /workflows endpoints

skema/skema-rs/skema/src/services/mathml.rs, skema/skema-rs/skema/tests/data/get_amr_payload.json, skema/skema-rs/skema/tests/test_service.rs
This PR adds a smokescreen unit test for the `/mathml/amr` PUT endpoint in the skema-rs REST API.
=> Adding smokescreen test for /mathml/amr PUT endpoint

skema/rest/workflows.py, skema/skema_py/server.py
Adds `system_to_enriched_system` function which takes a System as input and attempts to return an enriched system with comments added. This is done by running the calling the Rust comment extractor proxy endpoint over the files in System.blobs.
**Notes:**
-  Due to a quirk of the fn-unifier, System.root_name must be set for automatic comment enrichment to work. Gromet will still be returned from the endpoint, but the comments will not be included. This only affects the fn-given-filepaths endpoint. fn-given-filepaths-zip will automatically determine the root_name.
Adds a call to `system_to_enriched_system` in `system_to_gromet`. Now any endpoint using this function (fn-given-filepaths, fn-given-filepaths-zip) will automatically attempt to extract and unify comments. 
Removes comment …
=> [skema-py] - Automatically enrich System with comments

skema/skema-rs/mathml/src/parsers.rs, skema/skema-rs/mathml/src/parsers/first_order_ode.rs, skema/skema-rs/mathml/src/parsers/interpreted_mathml.rs, skema/skema-rs/mathml/src/parsers/math_expression_tree.rs, skema/skema-rs/skema/src/services/mathml.rs
This PR implements support for parsing presentation MathML in general with a small amount of preliminary interpretation (e.g., Globbing `S(t)` to produce the identifier `S`. Previously, this functionality was restricted to first order ODE parsing, but has been extended to parsing arbitrary expressions as well. This is the default behavior when `MathExpressionTree` structs are constructed from strings. The interpreting parsers are in `interpreted_mathml.rs`
The previous 'non-interpreting' parsers are still available in `generic_mathml.rs`, and are kept for compatibility with ISA code. Some of them are also reused in `interpreted_mathml.rs`
=> Support for parsing MathML with light interpretation

skema/skema-rs/mathml/src/parsers/interpreted_mathml.rs
interpreted_mathml.rs handles parsing Msub as a content identifier.
=> Msub as a content identifier

skema/program_analysis/TS2CAST/node_helper.py, skema/program_analysis/TS2CAST/preprocessor/preprocess.py, skema/program_analysis/TS2CAST/ts2cast.py, skema/program_analysis/TS2CAST/util.py, skema/program_analysis/TS2CAST/variable_context.py, skema/program_analysis/multi_file_ingester.py
Previously,  we were generating our own Dict tree based off of the tree-sitter parse tree. This allowed us to make a few quality of life optimizations such as removing nodes representing control characters like '+' and '=='. 
The code has now been refactored to remove this step. This change decreases processing time and will make it easier to support other tree-sitter languages in the future. 
In its place, multiple helper functions have been defined in node_helper.py to better support working with tree-sitter Node objects.
The tree-sitter parsing of the Fortran source code has been moved out of the preprocessor and into ts2cast.py. Overall, it makes more sense for the preprocessor to return source code rather than a parse tree.
We are now support generating CAST for the Record idiom in …
=> [code2fn] - Support for Fortran Record Idiom and TS2CAST enchancements

skema/skema_py/server.py
Switches from using System.model_validate to System.parse_obj. The former is not compatible with Python version 3.8
=> [code2fn] - Pydantic model_validate fix 

skema/rest/workflows.py
There was a bug in the amr workflows caused by using the wrong http request method when communicating with the skema-rs services. This has been fixed by switching these requests from POST to PUT.
Additionally, the regnet endpoints `code_snippets_to_rn_amr` and `repo_to_rn_amr` have been temporarily disabled because they are outdated.
=> [rest] - Fixing snippets-to-pn-amr and repo-to-pn-amr

skema/skema-rs/skema/src/bin/skema_service.rs
This adds version tracking from and environment variable named: APP_VERSION
If no variable is given it defaults to ?????
This will setup the version as the openapi docs version and there is a new endpoint that pulls the version. 
(Gus I think you need to add stuff to the docker compose files still for this?)
=> Skema-rs version tracking

skema/rest/api.py, skema/skema-rs/skema/src/bin/skema_service.rs
This PR ensures the response type for /version is set to plaintext.
=> response type for GET /version should be plaintext

skema/skema-rs/mathml/src/parsers/first_order_ode.rs, skema/skema-rs/mathml/src/parsers/generic_mathml.rs, skema/skema-rs/skema/src/services/mathml.rs
- `/mathml/amr` and `/mathml/petrinet`. The following errors have been added
- MISSING STARTING <math> TAG.
- INVALID DERIVATIVE ON LHS.
- MISSING EQUALS SIGN.
- COULD NOT PARSE RHS.
- MISSING ENDING </math> tag.
- `/mathml/ast-graph`. The errors are only the generic `ParseError` generated by nom with no additional specificity. 
-  Attempts to add specific errors to the generic MathML parser resulted in the errors only catching missing ending math tags even when it was only an intermediate tag that was missing. Adding specificity to `generic_mathml.rs` will require a deeper dive to solve.
- Added a public function called `append_message` to the `ParseError` struct to allow for updating the error message as it is propagated upwards through nom and our own parsers. It only appends messages …
=> Improved Error Handling mathml/amr, mathml/petrinet and mathml/ast-graph endpoints

skema/rest/workflows.py, skema/skema-rs/mathml/src/parsers/first_order_ode.rs, skema/skema-rs/mathml/src/parsers/generic_mathml.rs
- Generic MathML Parser Error update:
- Added tag level errors to `generic_mathml.rs` parser: `<mi>`, `<mn>`, `<msup>`, `<msub>`, `<msqrt>`, `<mfrac>`, `<mrow>`, `<munder>`, `<mover>`, `<msubsup>`, `<mtext>`, `<mstyle>`, `<mspace>`, `<mo>`.
- `/mathml/ast-graph` endpoint now shows these errors.
- 
- First Order ODE Parser Error update:
- Updated `ParseError` messages using the `context` combinator, removing the previous macro usage.
- The generic MathML errors were excluded as this parser uses `interpreted_mathml.rs`, which doesn't encounter those errors at the math_expression level.
- `/pmml/equations-to-amr` and `/latex/equations-to-amr` are passing on these errors. from `skema-rs`
- Lookahead Algorithm:
- Solved the problem of adding tag level parse errors by implementing a lookahead …
=> Generic MathML Errors using Parser Lookahead (some endpoints updated)

skema/skema_py/server.py
accidentally commented out a field I shouldn't have when updating the documentation example
=> fixed something I shouldn't have commented out

skema/rest/tests/test_integrated_text_reading_proxy.py
This is a temporary fix to issue #441, while we mock the COSMOS service
=> Temporarily commented out unit tests

skema/skema-rs/mathml/src/parsers/first_order_ode.rs, skema/skema-rs/mathml/src/parsers/interpreted_mathml.rs
Added msub identifie support for state variables in first order ode.
=> Incorporated msub identifier for state variables in first order ode

.github/workflows/docker.yml, skema/text_reading/scala/webapp/app/controllers/HomeController.scala, skema/text_reading/scala/webapp/conf/application.conf, skema/text_reading/scala/webapp/conf/routes, skema/text_reading/scala/webapp/docker.sbt
- Replaces the building and publishing of a text reading image that packages a CLI runnable in favor of one that packages a webapp exposing REST services.  
- Introduces the `/version` endpoint to the text reading web app (following similar REST endpoints in `skema-py` and `skema-rs`)
- Exposes ENV variable for application secret
- Resolves path problem with runnable (previously `text_reading` was missing)
- Resolves #446 
- Resolves #447 
- Resolves #449
=> Create and publish docker image for text reading webapp

skema/skema-rs/mathml/src/parsers/first_order_ode.rs, skema/skema-rs/mathml/src/parsers/interpreted_mathml.rs
Incorporated Unicode support for Newtonian derivative:  
Unicode for `˙` is  `&#x02D9;` in MathML representation for Newtonian derivative.
=> Unicode support for newtonian derivative

.github/workflows/docker.yml
Resolves a CI issue related to an action that removes unused packages to create additional space on the runner for docker builds
=> [CI] Use fork with fix to jlumbroso/free-disk-space/issues/9

.github/workflows/docker.yml, skema/text_reading/scala/webapp/build.sbt, skema/text_reading/scala/webapp/conf/application.conf
=> Increased the timeouts to handle long PDFs gracefully

skema/program_analysis/CAST/pythonAST/py_ast_to_cast.py, skema/program_analysis/CAST2FN/ann_cast/to_gromet_pass.py, skema/program_analysis/tests/test_primitive.py
- The handler that creates the GroMEt elements related to function calls needed a rewrite due to it becoming very difficult to maintain and change when bugs were discovered.
- The main goal was to make the code significantly smaller, and to remove redundancy and streamline the process as much as possible.
- The biggest redundancy changes was with the argument handling, as it was being done an unnecessary amount of times.
- There was also inconsistency with pof port generation and then it was needed and not needed. This caused inconsistent wiring generation.  
- A test file was added to support checking Gromets of small example programs that exercise the generation of function calls for both normal and primitive function calls.
- Python stores multi-line comments as docstrings. These don't …
=> GroMEt Function Call Handler Rewrite PR

pyproject.toml, skema/program_analysis/CAST/fortran/preprocessor/fixed2free.py, skema/program_analysis/CAST/fortran/preprocessor/preprocess.py, skema/program_analysis/CAST/fortran/tests/test_tiegcm.py, skema/program_analysis/tree_sitter_parsers/build_parsers.py, skema/program_analysis/tree_sitter_parsers/languages.yaml
Attempts to convert fixed-form Fortran source code to free-form before parsing with tree-sitter. Since there is no consistent way of checking if a Fortran source if fixed-form, we run the tree-sitter parser both before and after converting to free-form to check if either returns a valid parse tree.
- Removes existing implementation for handling fixed-form continuation lines.
- Adds testing framework for testing parsing TIE-GCM with tree-sitter.
Adding an optional `commit_sha` field to languages.yaml to specify the commit to use when building a tree-sitter parser. If not specified, the most recent commit will be used instead. 
```YAML
fortran:
tree_sitter_name: tree-sitter-fortran
clone_url: https://github.com/stadelmanma/tree-sitter-fortran.git
commit_sha: f73d473 …
```
=> [fortran] Support for fixed-form source and pinned tree-sitter-parser

.github/workflows/tests-and-docs.yml, docs/changes.md, mkdocs.yml, pyproject.toml
- Pins multiple dependencies for fewer surprises between builds
- Introduces explicit `beartype` dependency (see https://github.com/pytorch/pytorch/pull/109510)
- Refactor shared deps between tr and img2mml extras to use `skema[ml]` with pinned dependencies.
- Include release notes for [v1.9.2](https://github.com/ml4ai/skema/releases/tag/v1.9.2) (includes changes introduced today)
- [PRs](https://github.com/ml4ai/skema/pulls?q=is%3Apr+is%3Amerged+merged%3A2023-09-04..2023-09-18)
- [resolved issues](https://github.com/ml4ai/skema/issues?q=is%3Aissue+is%3Aclosed+closed%3A2023-09-04..2023-09-18)
=> List and pin transitive dependency

skema/text_reading/scala/webapp/test/controllers/HomeControllerSpec.scala
This is to make sure we don't again accidentally remove the brat library files. The test isn't conducted the usual way with a FakeRequest. That doesn't seem to work and there was indication in forums that the assets simply aren't available during test. Indeed, favicon.ico cannot be routed, for example. So, I'm just checking that the files haven't been removed from the development environment.
=> Check for the brat assets

pyproject.toml
Adds `skema[ml]` as a dependency in `skema[metal]` to more easily enforce dependency versions of PyTorch and related deps.
=> Use skema[ml] as dep in skema[metal]

.github/workflows/docker.yml
The CI step for building the TR docker image often fails or takes an inordinate amount of time to build and publish (ex. 2 hours).
Culprits include the the clulab JFrog repo which sometimes times out when we attempt to download (big) artifacts and the issues related to the large image size.
Our AWS deployment does not include the TR service (but may in the future if RAM consumption is reduced).  Until this PR, a failing TR image build & publish step would prevent a redeployment of our AWS service.
=> continue on error for TR docker builds

.github/workflows/text-reading-docker.yml
These changes attempt to remove additional default packages from the base runner to create some additional space for TR image build and publish step.
=> [CI] Additional tricks to save space building and publishing TR image

skema/text_reading/scala/webapp/docker.sbt
Our CI is using Temurin 11 for running our Scala tests, but our docker image was using temurin 8 as its base image.  Both now use Temurin 11.
Resolves #551
=> [TR] UseJava 11 in CI tests and for docker base image

skema/text_reading/scala/webapp/docker.sbt
Previously, `dockerBaseImage` was set in a manner that prevented it from being picked up.  This meant that any change to that setting was ignored and left at its default value.  With this PR, the setting now works as expected:
```bash
sbt "webapp/docker:stage"
head -n 1 webapp/target/docker/stage/Dockerfile
```
```dockerfile
FROM eclipse-temurin:11-jre-focal as stage0
```
Resolves #551
=> Resolves #551

skema/skema_py/server.py, skema/skema_py/tests/test_server.py
Adds an additional endpoint `gromet-object-count` to code2fn REST API. The endpoint accepts a Gromet dictionary (the response type from fn-given-filepaths and fn-given-filepaths-zip) and returns a dictionary with the counts of each Gromet object. It also contain aggregate values for the number of boxes, ports, and wires. 
``` Python
system = {
"files": ["example1.py", "dir/example2.py"],
"blobs": [
"greet = lambda: print('howdy!')\ngreet()",
"#Variable declaration\nx=2\n#Function definition\ndef foo(x):\n    '''Increment the input variable'''\n    return x+1",  # Content of dir/example2.py
],
}
response = client.post("/code2fn/fn-given-filepaths", json=system)
gromet_collection = response.json()
response = client.post("/code2fn/gromet-object-count", json=gromet_collection)
```
``` Python …
```
=> [code2fn] Adding gromet-object-count endpoint

skema/rest/integrated_text_reading_proxy.py
We now support processing cosmos json files directly from the `integrated-text-reading` endpoint.
If a pdf is preprocessed, the intermediate artifact will be used directly, speeding up things
=> Added support for cosmos json files

skema/skema-rs/mathml/src/acset.rs
This is an update to the id's in the AMR. The id field could be interpretted as an expression at some point so `-` might be confused for subtraction signs, so I removed them as possible characters in the uuids.
=> Update to AMR id's to not have -

skema/skema-rs/mathml/src/parsers/decapodes_serialization.rs, skema/skema-rs/mathml/src/parsers/interpreted_mathml.rs, skema/skema-rs/mathml/src/parsers/math_expression_tree.rs
Incorporated Superscript of right hand side parenthesis (e.g.`)^{n+1}`) and test case for decapodes ASCet serialization of Halfar dome equation 8.2 from CISM documentation
=> Incorporated Decapodes Ascet serialization of Halfar dome equation 8.2 from CISM documentation

skema/rest/utils.py, skema/rest/workflows.py, skema/skema-rs/skema/src/model_extraction.rs
This adds a util function to the REST API that takes in a function network and checks for all known bugs that can cause a deserialization error downstream. It then addresses the bugs in a generic fashion to allow serialization (although the FN is not correct, just digestible). It also outputs a log which contains every bug it has found and recording the type of bug and where the bug is inside the FN. 
I call this FN-Preprocessing on the FN's generated in the larger workflows as well. 
I also setup some error handling incase the dynamics could not be parsed in code2amr. Returning a blank/default AMR instead of a crash.
=> Fn-Preprocessing

skema/rest/morae_proxy.py, skema/skema-rs/mathml/src/parsers/decapodes_serialization.rs, skema/skema-rs/skema/src/bin/morae.rs, skema/skema-rs/skema/src/bin/skema_service.rs, skema/skema-rs/skema/src/services/mathml.rs
This should add an endpoint that takes in a list of MathML strings in and returns a DecapodeCollection, which is mainly a vector of Decapodes, one for each input MathML string.
=> Decapodes endpoint

skema/rest/metal_proxy.py
This change makes the endpoint support either json text extractions or directly the output of the `annotate_pdf` endpoint
=> [METAL][TR] Updated the `link_amr` endpoint to support better json payloads

pyproject.toml, skema/rest/api.py, skema/rest/llm_proxy.py, skema/rest/proxies.py, skema/rest/tests/test_llms.py
This is for an added endpoint that takes in a zip file containing a python script and returns the line span the dynamics should be under. 
It currently uses an Openai LLM for this, but we will replace that with a custom local model once it's ready.
=> Model linespan endpoint

pyproject.toml
https://github.com/ml4ai/skema/pull/601 introduced LLMs using `langchain` and the Open AI API.  The `llms` extra was included in the extra `all`, but our docker image only installs `core` to avoid bloat:  https://github.com/ml4ai/skema/blob/3af73f74ec127e0fb4c5abf4d3a8f9bd0eea3e71/Dockerfile.skema-py#L53
This caused an import error that triggered a deployment failure loop.
=> Ensure `skema[llms]` included in docker image build

Dockerfile.skema-py
[Nodesource changed their Node JS binary installation process back in August](https://github.com/nodesource/distributions/pull/1626).  This seems to have finally caught up with us.
[This PR shifts to the new installation method](https://github.com/nodesource/distributions#nodejs).
=> Pin node minor version to avoid occasional CI issue

pyproject.toml, skema/rest/utils.py, skema/skema-rs/skema/src/bin/morae.rs, skema/skema-rs/skema/src/database.rs
Expanded the function network preprocessing to handle -1's in the metadata for 'line_begin', 'line_end', 'col_begin', and 'col_end'. 
Also added some checks into database.rs, to stop some crashes.
=> More Fn-Preprocessing

skema/program_analysis/CAST/matlab/matlab_to_cast.py, skema/program_analysis/CAST/matlab/node_helper.py
This PR fixes the if statement handler in `matlab_to_cast.py`.  We now fully support `if elseif else` conditional logic of arbitrary depth in MATLAB.
- One `if` statement is always included
- Zero or more `elseif` clauses can be included
- Zero or one `else` clause can be included
Completes issue #593
Partially completes  issue #561
=> MATLAB conditional logic 

skema/program_analysis/CAST/matlab/cast_out, skema/program_analysis/CAST/matlab/matlab_to_cast.py, skema/program_analysis/CAST/matlab/tests/test_assignment.py, skema/program_analysis/CAST/matlab/tests/test_binary_operation.py, skema/program_analysis/CAST/matlab/tests/test_conditional_logic.py, skema/program_analysis/CAST/matlab/tests/utils.py, skema/program_analysis/CAST/matlab/tree_out
This PR includes some test utilities for use when testing CAST output, so common tests such as an assignment or an expression can be done as single function calls.  Some debug scripts are now executables.   Minor edits and code cleanup
- Added `skema/program_analysis/CAST/matlab/tests/utils.py` with functions for common testing tasks
- Added 3 conditional logic tests:
`if`
`if else`
`if elseif else`
Related to PR #613 and #583
=> CAST test upgrades

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/tests-and-docs.yml, skema/rest/tests/test_integrated_text_reading_proxy.py, skema/rest/tests/test_model_to_amr.py
- backgrounds skema-rs REST API in CI for testing Python-based REST workflows
- adds a field to PR template to list related or resolved issues
- log value of `SKEMA_RS_ADDRESS` env variable in python unit tests that use it
Resolves #667
=> Use local skema-rs service in CI testing of Python

skema/rest/llm_proxy.py, skema/rest/tests/test_model_to_amr.py, skema/rest/workflows.py
I believe for multiple files in the zip drive we hit the code2fn and code-snippets endpoint too rapidly and they sometimes crash, resulting in inconsistent response times and results from the LLM endpoint. I added 0.5 second sleeps before each endpoint call to not overload them. The exact sleep time can be refined and shrunk down as we understand it better. 
Resolves ???
=> Consistent Response times for LLM related endpoints

skema/skema-rs/mathml/src/parsers/math_expression_tree.rs
- Handle negative minus and sqrt in `to_latex` and add tests for mtext.
=> [img2latex] Handle negative minus and sqrt in to_latex and add tests for mtext

skema/program_analysis/CAST/python/node_helper.py, skema/program_analysis/CAST/python/ts2cast.py, skema/program_analysis/CAST2FN/visitors/cast_to_agraph_visitor.py, skema/program_analysis/tests/test_expression_cast.py, skema/program_analysis/tests/test_for_cast.py, skema/program_analysis/tests/test_identifier.py, skema/program_analysis/tests/test_while_cast.py
This PR introduces support for generating CAST for Loops (for/while) using tree-sitter, as part of the ongoing effort to port over the Python AST to CAST generation to using tree-sitter.
- Added support for generating CAST Loop nodes using Python tree sitter.
- Specifically, we added support for Python's For and While loop CAST generation. 
- Added some support for tree-sitter "patterns: "list_pattern", "tuple_pattern", "list_pattern". These are used primarily in the For loop syntax as the item we're iterating over.
- Also added support for generating Iterator function calls, as used by the Python For Loops.
- Updated the CAST to AGraph visualizer to better visualize tuples.
- Added some small unit tests for loops (for/while) to determine consistency. 
- Added a small unit test for …
=> Python tree-sitter to CAST porting: Loops

skema/rest/tests/test_integrated_text_reading_proxy.py, skema/rest/utils.py
Updated the TR grading code to stop double counting automated extractions which lead to an incorrect amount of true positives.
There is a many to one relationship between SKEMA extractions and manual annotations. Multiple extractions can match an annotation (be correct). To compute P, R and F1, all the extractions associated to a manual annotation should be counted as a single true positive.
This change addresses this issue.
Resolves 755
=> Fixed #755

skema/rest/workflows.py, skema/skema-rs/mathml/src/ast.rs, skema/skema-rs/mathml/src/ast/operator.rs, skema/skema-rs/mathml/src/parsers/math_expression_tree.rs, skema/skema-rs/skema/src/bin/skema_service.rs, skema/skema-rs/skema/src/services/gromet.rs
This PR adds a new Rust side endpoint that converts gromets to a vector of MET. This will be of use as we rollout more ISA based workflows. 
This also added a commented out endpoint stub in workflows.py for taking in code-snippets and converting them into a vector of MET's as well, to further lay some foundation for ISA workflows. 
Resolves ???
=> Code2MET Rust Endpoint

skema/program_analysis/CAST2FN/ann_cast/to_gromet_pass.py, skema/program_analysis/tests/test_literal_returns.py
This PR primarily fixes a crash in the Gromet generation when there's a While loop condition consists only of a function call. 
It also fixes another minor wiring bug related to LiteralValues
- Fixed Gromet generation crash for While loop condition of a function call.
- Fixes a missing wiring bug when a function returns a plain LiteralValue.
- Adds some small unit tests to maintain consistency.
Resolves #728
=> Gromet While Loop Wiring Bug PR

skema/program_analysis/CAST/fortran/ts2cast.py, skema/program_analysis/CAST2FN/ann_cast/cast_to_annotated_cast.py, skema/program_analysis/CAST2FN/ann_cast/to_gromet_pass.py, skema/program_analysis/CAST2FN/visitors/cast_to_agraph_visitor.py, skema/program_analysis/tests/test_goto_computed.py
- Adds CAST support for ingesting Computed GO TO
- Adds support for generating GroMEt for CAST files containing Computed GO TOs. 
- Adds a test script `test_goto_computed.py` that contains a unit test for a small Fortran file that has a Computed GO TO. 
- Fixes a small issue in the Annotated CAST generation in `cast_to_annotated_cast.py`. This fix allows correct support of Computed GO TOs.
- Updates CAST Visualizer to support visualizing GO TO and Label CAST nodes.
Since the expression in Computed GO TOs evaluates to an index rather than a label, we make a small conversion to the expression in the CAST to support this. We utilize the _get Gromet function to handle this indexing.
So:
```fortran
GO TO (100,200,300,400), x+y
```
gets converted to:
```python
_get(["100", "200", "300", "400"], …
```
=> [fortran] Support for Computed GO TO 

skema/rest/tests/test_model_to_amr.py, skema/rest/workflows.py
This PR added a CI test for LaTeX to Regnet. 
It also added a new endpoint for code snippets to MathExpressionTree
Resolves part of issue #770
=> Adding CI workflow tests

skema/skema-rs/mathml/src/parsers/generic_mathml.rs
Fix the parser error when handling "∕".
=> [Equations] fix the divide error in parser

pyproject.toml
On March 10th the tree-sitter Python library updated to version 0.21.0. This version breaks many of our unit tests due to changes in language initialization. 
This PR pins the version to 0.20.4, the last working version, so that the unit tests work again. 
Resolves ???
=> [CI] Pinning tree-sitter to 0.20.4

skema/skema-rs/mathml/src/acset.rs, skema/skema-rs/mathml/src/parsers/decapodes_serialization.rs, skema/skema-rs/mathml/src/parsers/first_order_ode.rs, skema/skema-rs/skema/src/bin/morae.rs, skema/skema-rs/skema/src/services/mathml.rs
This addresses some bug that TA4 pointed out in our Regnet generation. Being generation of correct initial condition id's and fixing the json schema for edges, being the `source` and `target` fields are scalars and not arrays. 
Resolves #851
=> Regnet Bug Fixes

pyproject.toml, skema/program_analysis/module_locate.py, skema/program_analysis/tests/test_module_locate.py
-Adds support for dependencies that are compiled into the Python interpreter like `time` and `sys`
-Adds and improves tests for module_locate module 
Resolves #782
Resolves #795
=> Adding tests for module_locate

skema/skema-rs/mathml/src/acset.rs
Fixed the default value for expression_mathml in the Initial struct for PetriNets
Resolves ???
=> Fixed default string for intitals mathml in PN

skema/rest/integrated_text_reading_proxy.py, skema/rest/schema.py, skema/rest/tests/test_integrated_text_reading_proxy.py
Added support for optional annotation of AMR linking to `integrated-text-extractions`
Resolves 856
=> Added support for optional annotation of AMR linking

skema/skema-rs/mathml/src/parsers/generic_mathml.rs
Fixed bug for not supporting un-escaped ∗
=> Fix * parse error

skema/skema-rs/mathml/src/acset.rs, skema/skema-rs/mathml/src/parsers/first_order_ode.rs, skema/skema-rs/skema/src/services/mathml.rs
- Fixes an issue where when a binary multiplication tree got too deep, we failed to fully flatten it, leading to Petrinet parsing errors. 
- Fixes an error with infix expressions, so should make it so if a transition has division in it, the infix expression will properly show that as well, instead of `*` like it was showing before. 
Resolves #868 #871 #403
=> Full Infix Notation Fix and Multiplication Tree Depth Bugfix
