.drone.yml
Adds `.drone.yml` file to the root of the repository for Drone.io continuous integration support
=> Drone.io CI support

.drone.yml, README.md
- README.md: - Added build status badge - Added short description
- .drone.yml: Updated pipeline and step names
=> Updates to README.md

skema/skema-rs/Cargo.lock, skema/skema-rs/skema/Cargo.toml, skema/skema-rs/skema/README.md, skema/skema-rs/skema/src/bin/morae.rs, skema/skema-rs/skema/src/bin/skema_service.rs, skema/skema-rs/skema/src/lib.rs, skema/skema-rs/skema/src/services/comment_extraction.rs, skema/skema-rs/skema/tests/test_service.rs
This PR adds automatic OpenAPI spec and Swagger UI generation from code for the SKEMA Rust web services. See screenshot for what this looks like:
=> SKEMA Rust services OpenAPI spec + Swagger documentation

notebooks/morae_demo.ipynb, skema/skema-rs/skema/src/bin/skema_service.rs, skema/skema-rs/skema/src/services/gromet.rs
Added query support for named ports reading
=> simple named port query

.drone.yml, skema/skema-rs/README.md, skema/text_reading/text_reading/build.sbt
This PR updates `.drone.yml` to trigger specific pipelines conditionally based on the paths of changed files.
Specifically:
- The `skema-rs` pipeline will only be triggered when files in the `skema/skema-rs` directory changes
-  The `skema_tr` pipeline will only be triggered when files in the `skema/text_reading/text_reading` directory change.
=> Updating CI to trigger conditionally on paths of changed files.

skema/skema-rs/skema/src/bin/gromet2graphdb.rs
* Added Clap CLI args support to rust_memgraph.rs
* Renamed rust_memgraph.rs to gromet2graphdb.rs
=> Updates to GroMEt JSON ingester program

Dockerfile.code2fn, skema/code2fn/client.py
This PR updates the Code2FN Dockerfile to use Python 3.8, and also updates the command line arguments for the Code2FN example client program.
=> Code2fn updates

pyproject.toml, skema/im2mml/generate_mathml/im2mml_demo.py
This PR updates pyproject.toml to properly work with extra features, adding extra optional dependencies for moviz and im2mml. It also fixes a bug in im2mml_demo.py
=> Im2MML updates

skema/im2mml/README.md
This PR updates the Im2MML README.md
- Adds a curl command to get the model.
- Adds instructions on running and testing the im2mml service without Docker.
=> Updated Im2MML documentation

skema/text_reading/text_reading/build.sbt, skema/text_reading/text_reading/grounding/build.sbt, skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/entities/RegexBuilder.scala, skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/entities/StringMatchEntityFinder.scala, skema/text_reading/text_reading/src/test/scala/org/ml4ai/skema/text_reading/entities/TestRegexBuilder.scala
Also migrate to artifactory.clulab.org
=> Remove dependency on regextools

skema/skema-rs/comment_extraction/README.md
Updated the README.md for the comment extraction module to specify its capabilities and limitations in more detail.
=> Updated README.md for comment extraction module

.drone.yml, skema/img2mml/api.py, skema/img2mml/img2mml.py, skema/img2mml/img2mml_cli.py, skema/img2mml/models/attention/bahdanau_attention.py, skema/img2mml/models/decoders/lstm_decoder.py, skema/img2mml/models/decoders/xfmer_decoder.py, skema/img2mml/models/encoders/xfmer_encoder.py, skema/img2mml/models/encoding/positional_features_for_cnn_encoder.py, skema/img2mml/translate.py, skema/img2mml/utils.py
This PR implements a number of updates to the im2mml pipeline:
- Refactors the code to get rid of the Image2Tensor class (there is no reason to have a class here, functions should serve just fine since the class did not have any state).
- Removes unneeded code
- Lowercases non-global variables.
- Performs a number of other code lints.
=> More Img2MML updates

skema/text_reading/mention_linking/gromet_explorer.py, skema/text_reading/mention_linking/gromet_linker/__init__.py, skema/text_reading/mention_linking/gromet_linker/comment_aligner.py, skema/text_reading/mention_linking/gromet_linker/text_reading_linker.py, skema/text_reading/mention_linking/gromet_linker/utils.py, skema/text_reading/mention_linking/link_mentions.py
Added an entry point for mention linking and fixed a bug of missing groundings
=> Mention linking entrypoint

.gitignore, skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/CosmosTextReadingPipeline.scala
This takes care of a bug where the determiners where merged to the previous word
=> Commented out WordBreakBySpacePreprocessor

skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/CosmosTextReadingPipeline.scala
Don't attempt to ground text bound mentions that are purely numerical values
=> Started fixed to grounding of mentions

skema/text_reading/mention_linking/gromet_linker/utils.py, skema/text_reading/mention_linking/link_mentions.py
There were some bugs on the gromet generated after linking. This PR fixes them (thanks to @titomeister and @vincentraymond-ua)
=> Bug fixes to gromet generated by mention linking

skema/text_reading/mention_linking/gromet_linker/text_reading_linker.py, skema/text_reading/mention_linking/link_mentions.py
=> Support multiple extraction files for alignment

skema/text_reading/mention_linking/gromet_linker/text_reading_linker.py, skema/text_reading/mention_linking/gromet_linker/utils.py
Added support for simplified json files from MIT extractions into the mention linking pipeline
=> Added support for MIT extractions for linking

skema/text_reading/mention_linking/gromet_explorer.py
It is updated to read multi-model gromets
=> Update to the gromet explorer script

skema/text_reading/text_reading/src/main/scala/org/ml4ai/skema/text_reading/OdinActions.scala
=> Fix bug that turned out to be in OdinActions

skema/skema-rs/skema/src/bin/skema_service.rs, skema/skema-rs/skema/src/lib.rs, skema/skema-rs/skema/src/services/comment_extraction.rs, skema/skema-rs/skema/src/services/gromet.rs
This PR implements some minor updates to the skema-rs REST API.
- The docs have been fixed so that all the required Gromet-related schemas show up.
- The gromet service paths are now bundled in a configure() method for increased modularity.
=> REST API updates

README.md, skema/program_analysis/CAST2GrFN/ann_cast/grfn_assignment_pass.py, skema/program_analysis/CAST2GrFN/ann_cast/to_gromet_pass.py, skema/program_analysis/CAST2GrFN/ann_cast/variable_version_pass.py, skema/program_analysis/CAST2GrFN/visitors/cast_to_agraph_visitor.py, skema/program_analysis/JSON2GroMEt/json2gromet.py, skema/program_analysis/PyAST2CAST/modules_list.py, skema/program_analysis/PyAST2CAST/py_ast_to_cast.py, skema/program_analysis/multi_file_ingester.py, skema/program_analysis/script_functions.py
Changes to Code2FN pipeline to support ingestion of Bucky full model.
See milestone 7 report for changes to the pipeline.
=> Milestone 7 PR

docs/generator.hs
This PR fixes a bug with the documentation generation program.
=> Bugfix for documentation generation

skema/program_analysis/CAST2FN/ann_cast/to_gromet_pass.py, skema/program_analysis/PyAST2CAST/builtin_map.py, skema/program_analysis/PyAST2CAST/py_ast_to_cast.py
This PR resolves the GroMEt generation issue by adding some missing checks in the code. The pipeline now generates GroMEt v0.1.6 for the Bucky model and the other epidemiology models. 
It also temporarily removes the yaml library as it isn't currently added as a requirement and breaks the test suite.
Fixes issue ml4ai/skema#166
=> Resolves ml4ai/skema#166

skema/text_reading/text_reading/cosmos_integration.py
This is a small fix for an issue reported by the cosmos team when running our image on their side.
=> Added a fix to skip empty cosmos files instead of crashing

skema/text_reading/text_reading/webapp/app/controllers/HomeController.scala, skema/text_reading/text_reading/webapp/conf/routes
=> Added an end point to handle plain text contents

skema/img2mml/api.py, skema/img2mml/data_generation/mathjax_server.js
Changed the mathjax server port to 8031 to align with our testing
=> Changed the mathjax server port to 8031

Dockerfile.skema-py, pyproject.toml
Introduces optional demo dependencies (ex.`skema["demo"]`) for convenience.
=> [demo] Add optional demo dependencies

pyproject.toml, skema/img2mml/data_generation/mathjax_server.js, skema/img2mml/eqn2mml.py, skema/rest/utils.py, skema/rest/workflows.py
With this PR, data is now passed correctly from code -> fn -> morae.  
Examples here: https://github.com/ml4ai/ASKEM-TA1-DockerVM/blob/3b5468c6ec7a19802eb0c5eff8fd9a0615bcf7de/end-to-end-rest/notebooks/code2amr.ipynb
All that's left are updates/adjustments to morae to handle the current version of gromet produced by code2fn.
=> [integration] code -> AMR endpoints

skema/skema-rs/comment_extraction/src/bin/extract_comments.rs, skema/skema-rs/mathml/src/acset.rs, skema/skema-rs/mathml/src/parsers/first_order_ode.rs, skema/skema-rs/skema/src/bin/morae.rs, skema/skema-rs/skema/src/services/gromet.rs
This is a small PR that:
- fixes a bug for the FN2AMR endpoints documentation
- does a preliminary first run at filling in the semantics for the PertriNet AMR
=> updates to amr semantics

.github/workflows/tests-and-docs.yml
- rename .github/workflows/docs.yml -> .github/workflows/tests-and-docs.yml
- add step for running unit tests for Rust-based components
=> [CI] Run unit tests for Rust components

skema/img2mml/README.md, skema/img2mml/eqn2mml.py
=> Update README.md for eqn2mml

skema/skema-rs/mathml/src/parsers/first_order_ode.rs
Small fix for a bug for eq2amr endpoints
=> bug fix for eq2amr

skema/rest/schema.py, skema/rest/workflows.py
This should expose the mathml2amr endpoint on the unified api. (Hopefully)
=> Endpoint tweaks

skema/rest/integrated_text_reading_proxy.py, skema/rest/metal_proxy.py
Added format and snippets to all TR and Metal endpoints
=> [TR][METAL] Improved the documentation of the endpoints

skema/skema-rs/mathml/src/parsers/first_order_ode.rs, skema/skema-rs/skema/src/bin/morae.rs
This is a small bug fix for the eq2amr pipeline. It was messing up Unary subtractions when inside a multiplication during the flatten_mults() function call. (It was a small scoping mistake)
=> Lieffers eq2amr bugs

skema/rest/integrated_text_reading_proxy.py, skema/rest/metal_proxy.py
Updated the dependency `askem-extractions`, so this PR is meant to trigger a build and update the deployment
=> Trigger a build to update the image and dependency

skema/rest/integrated_text_reading_proxy.py
Caused by the migration from pydantic 1 to 2
=> [TR] Fixed an MIT deserialization problem

skema/rest/tests/test_integrated_text_reading_proxy.py
Added unit tests for the TR REST endpoints
=> [TR] enoriega/tr unit tests

.github/workflows/docker.yml, Dockerfile.skema-rs
=> Use Git commit short hash for skema-rs version

skema/skema-rs/mathml/src/acset.rs
Updated the AMR data struct to have a header
=> Updated AMR with header

docs/dev/creating-an-incremental-release.md, mkdocs.yml
Introduces a new section of the developer documentation that outlines the steps to create a new incremental software release.
=> [docs] Instructions for creating an incremental release

skema/text_reading/scala/build.sbt
This will help reduce the image size
=> [TextReading] Removed Space Weather embeddings

skema/rest/integrated_text_reading_proxy.py, skema/rest/proxies.py
=> [TextReading] Fixes TR endpoints in REST API

.github/workflows/docker.yml, .github/workflows/text-reading-docker.yml, docs/changes.md
- Make TR image creation and publishing its own workflow
- Update changes.md with notes on pending release
=> [CI] Make TR docker build its own workflow

skema/skema-rs/skema/src/database.rs
This is small bug fix that was causing issues for wiring primitives that was making the endpoint crash.
=> Small bug fix for database.rs

docs/changes.md
Documents changes (in terms of dates) for v1.9.4.
=> [release] Record of changes for v1.9.4

skema/skema-rs/skema/src/bin/morae.rs, skema/skema-rs/skema/src/database.rs
This PR adds initial support for Conditional and While loops called at the top level. 
It also has a work around for `if __main__:` statements for a code2amr bug
=> Conditional and While Loop initial support

skema/skema-rs/mathml/src/acset.rs
Reverted amr id to previous representation. 
Still need to make check to make sure amr id's from code conform to specs
=> revert for amr id changes

skema/rest/schema.py, skema/rest/utils.py
Now we report full P/R/F1 for the text extractions given a baseline GT annotated pdf
=> [TR] Improved the text extractions evaluation endpoint

skema/rest/morae_proxy.py, skema/rest/utils.py, skema/skema-rs/skema/src/database.rs
There was a bug on primitive creation and made the error handling for duplicated edges better.
=> Fixed some small bugs for code2amr

skema/rest/llm_proxy.py
I forgot to change LineSpan to Dynamics in the function def when I changed to the struct the HMI folks wanted.
=> Fixed outdated data struct

.github/PULL_REQUEST_TEMPLATE/summary_of_changes.md, .github/labeler.yml, pyproject.toml
Adds a PR template for greater consistency, as well as new auto-label triggers for PRs.
=> [CI] PR template and new auto-labels for PRs

skema/rest/tests/test_integrated_text_reading_proxy.py
This will restore the CI functionality while Hopper is down
=> Disabled the TR tests for the weekend

skema/rest/llm_proxy.py, skema/rest/workflows.py
I had a typo in the LLM endpoint that was missed by the mocked up test case. I will be adding additional test cases that should make the testing of this endpoint more robust soon. 
Resolves ???
=> fixed a typo in the LLM endpoint

skema/rest/llm_proxy.py, skema/rest/tests/test_model_to_amr.py, skema/rest/workflows.py
Fixed several a small bug in llm-assisted-codebase-to-pn, updated the chime sir test to the new version of the endpoint 
Resolves ???
=> Small morae fix 2

skema/skema-rs/mathml/src/parsers/math_expression_tree.rs
Change "/" to "\frac" in the latex expression output
=> [img2latex] Change "/" to "\frac" in latex expression

skema/rest/llm_proxy.py, skema/rest/tests/test_model_to_amr.py, skema/rest/workflows.py
Fixed 2 small bugs, optimized some, and added some error handling and logging
- One, was the descriptions wasn't getting reset for each file
- Two, was that we weren't slicing the blobs and files correctly to send to code-snippets, causing a timeout error
- Three, I optimized the linespan endpoint some for multi-file systems, it was initializing the LLM for each file, which I doesn't need to. 
- Four, I added some error handling incase some file's fail in parsing into AMR's. I also log those failures and if we get no AMR's, I return the logs instead, so we at least know what was tried. 
Resolves ???
=> Small Morae fix 3

skema/rest/tests/test_model_to_amr.py, skema/rest/workflows.py
Adding some logging for the llm-assisted-code2amr endpoint.
Added better support for when code-snippets fails to extract dynamics.
Resolves ???
=> Better Logging and Error handling for LLM endpoints

docs/dev/docker.md
- Updates build instructions for text reading image (1. Dockerfile generation, 2. Image build)
=> [documentation] Updates to docker build instructions

skema/rest/api.py
Fixes typo in environment-variables endpoint that was causing issues with deployment
=> [rest] Fixing typo in environment-variables endpoint

.github/workflows/docker.yml, .github/workflows/text-reading-docker.yml
- Always attempt to pull when building a docker image (to avoid using an outdated base image)
- Disable cache during image builds (to help surface potential problems)
- Bump versions of docker actions
=> Changes to docker build settings

skema/rest/workflows.py, skema/skema-rs/skema/src/database.rs
Fixed a bug for when we add imports to code2amr
Resolves ???
=> Fixed small bug for imports

skema/img2mml/eqn2mml.py, skema/isa/data.py, skema/isa/isa_service.py, skema/isa/lib.py, skema/rest/api.py, skema/rest/tests/test_isa.py, skema/skema_py/server.py, skema/skema_py/tests/test_server.py
- Explicitly return a status code of 200 for calls to /version.
- Support head calls to /version.
- Changed ISA PUT request to a POST
- Renamed file1 and file2 to `mml1` and `mml2` (in the REST API, these will **always** be "file" contents (i.e., MML).
- Added ISA test case data to `isa/data.py` for ease of use between ISA tests and API docs.
- Refactor status codes to use constants for better consistency.
- Temporarily disable ISA router (deployment debugging)
=> [REST] Refactor for improved consistency

skema/program_analysis/CAST/matlab/matlab_to_cast.py, skema/program_analysis/CAST/matlab/tests/utils.py, skema/program_analysis/CAST2FN/visitors/cast_to_agraph_visitor.py
- Adds a validation test to detect GroMEt issues
- Added a Character scalar type
Resolves #731
=> CAST to GroMEt bugfix

skema/rest/llm_proxy.py, skema/rest/workflows.py, skema/skema_py/server.py, skema/skema_py/tests/test_server.py
- Refactors validation handler in system2gromet to support more complex cases.
- Adds check for files in hidden directories to code2fn endpoints.
- Adds check for MACOS artifacts to code2fn endpoints.
- Generates logging for new validation checks to stdout and Gromet. 
- Adds a test case for validating hidden files and MACOS artifacts.
- Fixes bug where file could be removed from system.files buts not system.blobs
#690 
Resolves #690
=> [code2fn] Additional validation for code2fn endpoints

skema/skema-rs/mathml/Cargo.toml, skema/skema-rs/mathml/src/expression.rs, skema/skema-rs/skema/Cargo.toml, skema/skema-rs/skema/src/services/gromet.rs, skema/skema-rs/skema/src/services/mathml.rs
Pinned the Rust dependency versions
Resolves ???
=> Pinned Rust dependencies

skema/program_analysis/easy_multi_file_ingester.py, skema/program_analysis/multi_file_ingester.py, skema/program_analysis/url_ingester.py
- Adds new code2fn frontend url_ingester.py to ingest systems from Git repositories.
- Fixes bug in in Gromet module index calculation where non-python sources wouldn't follow the proper dot notation
- Updates docstring for easy_multi_file_ingester.py
Resolves #783
=> [code2fn] Additional frontend url_ingester.py 

skema/skema-rs/mathml/src/parsers/math_expression_tree.rs
Remove redundant parentheses when converting pMathML to LaTeX.
=> [Equations] Remove redundant parentheses when converting pMathML to LaTeX

skema/rest/schema.py, skema/rest/workflows.py, skema/skema-rs/mathml/src/acset.rs
This PR adds:
- More documentation for the new consolidated endpoints. 
- Fixed default values for the Petrinet struct
- Added new error handling workflow for if Petrinet or Regnet fails, we attempt to output a Generalized AMR
Resolves ???
=> Added more documentation, expanded error handling, fixed default values

skema/rest/schema.py, skema/rest/workflows.py
Fixed some documentation errors and a typo in the consolidated endpoint
Resolves ???
=> Fixed some documentation errors

skema/text_reading/scala/src/main/scala/org/ml4ai/skema/text_reading/cosmosjson/CosmosJsonProcessor.scala
Fixes an issue with processing of cosmos files with weird characters that tripped the TR pipeline
Resolves 829
=> Fixes issue #829

skema/skema-rs/mathml/src/acset.rs
There was a bug for too many src's and tgt's for certain equations. Fixed it. 
Resolves ???
=> Fixed regnet bug

skema/text_reading/scala/src/main/scala/org/ml4ai/skema/text_reading/CosmosTextReadingPipeline.scala, skema/text_reading/scala/webapp/conf/application.conf
Properly handles document chunks that crash the Odin engine and gracefully continues with the remaining of the inputs
Resolves 835
=> Fixes issue #835

skema/metal/model_linker/skema_model_linker/linkers/petrinet.py
Fix for bug reported on #869
Resolves #869
=> Bugfix for linking petrinets
